### ISSUE TITLE
Answer to a callback button

### ISSUE THREAD

**Issue by albo94** [ocordova/ama#1]
Good evening!
Firstly thank you very much for your beautiful and helpful guide:
http://ocordova.me/blog/telegram-bot-with-apps-script
Your telegram bot works great, but now I would like to add a callback button:
`function doPost(e) {
  var update = JSON.parse(e.postData.contents);
  var msg = update.message;   
  var chatId = msg.chat.id;

  if (msg.text == '/example') {
    var payload = {
      'method': 'sendMessage',
      'chat_id': String(chatId),
      'text': 'message',
      "parse_mode": "Markdown",
      'reply_markup': JSON.stringify(
        {
          'inline_keyboard': [[{text: 'button1', callback_data: '1'},{text: 'button2', callback_data: '2'}]],
          'switch_inline_query': false
        }
      )
    }
    var data = {
      "method": "post",
      'contentType': 'application/json',
      'payload' : JSON.stringify(payload)
    }
    token = 'TOKEN';
    indirizzo = 'https://api.telegram.org/bot' + token + '/';
    UrlFetchApp.fetch(indirizzo, data);    
  }
}`
<img width="721" alt="problem" src="https://user-images.githubusercontent.com/20287100/29743335-28ffa9b6-8a90-11e7-80a4-f062ea9f5714.png">
You can see this feature also in the Telegram bot api. There is a video in the section  ‘updating messages’ at link https://core.telegram.org/bots/2-0-intro that explains it very well.
The practical example shown in that video is the bot @music when pressing on 'load more'.

I don't know if you know how it is possible to implement this feature with Google Apps Script.
Thank you very much for reading
Every suggestion will be very appreciated!
Have a nice evening

**Comment by ocordova** [comment]
Sorry it took me so long to reply.

I did some tests and it is pretty straightforward:

Once you send the message that contains the _inline_keyboard_, when you press a button, you will receive a **callback_query** response similar to this example:
```
{
   "update_id":720713151,
   "callback_query":{
      "id":"45569782854285423",
      "from":{
         "id":10610041,
         "is_bot":false,
         "first_name":"u00d3s (Human)",
         "username":"oscordova",
         "language_code":"en-GB"
      },
      "message":{
         "message_id":451,
         "from":{
            "id":256245790,
            "is_bot":true,
            "first_name":"u00d3s (Bot)",
            "username":"ocordovaBot"
         },
         "chat":{
            "id":10610041,
            "first_name":"u00d3s (Human)",
            "username":"oscordova",
            "type":"private"
         },
         "date":1505767564,
         "text":"hi"
      },
      "chat_instance":"3846801533409951215",
      "data":"A1"
   }
}
```
And you need to use the [editMessageText](https://core.telegram.org/bots/api#editmessagetext) method to reply, don't forget to send the value _chat_id_, _message_id_, _text_ and the inline_keyboard.

![reply](https://user-images.githubusercontent.com/694736/30603098-2351b0aa-9d2c-11e7-84a8-31de16a04176.gif)

**Comment by linglung** [comment]
Can you explain more to this point: 

> And you need to use the editMessageText method to reply, don't forget to send the value chat_id, message_id, text and the inline_keyboard.

i am stuck to catch `callback_query` at the beginning. Is it something like below:

`     if (callback_query.text == 'A1') { blah blah}` 

or something like 

```
function doPost(e) {
   var update = JSON.parse(e.postData.contents);
   var msg = update.message; 
   var chatId = msg.chat.id;
   var payload = {
       'method': 'sendMessage',
       'chat_id': String(chatId),
       'text': 'message',
       "parse_mode": "Markdown",
       'reply_markup': JSON.stringify(
           {
            'inline_keyboard': [
                [
                   {text: 'button1', callback_data: 'A1'},
                   {text: 'button2', callback_data: 'A2'}
                ]
            ],
             'switch_inline_query': false
           }
     )
  }
     var data = {
           "method": "post",
           'contentType': 'application/json',
           'payload' : JSON.stringify(payload)
    }
UrlFetchApp.fetch(url, data);
```
**then this is i am stuck here**
```
if (msg.callback_query.text == 'A1') {  // if (msg.callback_query.data== 'A1') { <---------
// or what's the correct thing
    var payload = {
         'method': "editMessage",
         'chat_id': String(chatId),
         'message_id': msg.message_id,  // or msg.id ?? 
         'text': 'changed text',
         "parse_mode": "HTML"
           }
   var data = {
        "method": "post",
        'contentType': 'application/json',
        'payload' : JSON.stringify(payload)
      }
UrlFetchApp.fetch(url, data);
}
```

An example code will be highly appreciated. I am truly a beginner for this. thank you so much

**Comment by ocordova** [comment]
You're almost there :wink:

Probably you're going to use the bot to receive commands too, so i recommend something like this:

```javascript
  var msg = update.message;

  if (msg && msg.entities && msg.entities[0].type == 'bot_command') {

    // Detect bot commands

  } else if (msg && msg.entities && msg.entities[0].type == 'mention') {

    // Maybe you want to detect mentions

  } else if (update.callback_query.data) {

    // Anyhthing related to callback queries
  }
```

Now you just need to reply... since you want to edit the last message not to create a new one, you need to use the **editMessageText** method.

Telegram needs to know which message you want to edit, so you need to provide the *message_id* Fortunatelly the *callback_query* has that id... your response will look something like this:

```javascript
{
      'method': 'editMessageText',
      'chat_id': String(update.callback_query.message.chat.id),
      'message_id': String(update.callback_query.message.message_id),
      'text': "test",
      'parse_mode': 'HTML',
      "reply_markup": JSON.stringify({
        "inline_keyboard": [
          [{
              "text": "A",
              "callback_data": "A1"
            },
            {
              "text": "B",
              "callback_data": "C1"
            }
          ]
        ]
      })
    }
```
Btw, you need to send the **inline_keyboard** because telegram will edit the message completely... of course if you don't want the user to press another button, just don't send it

**Comment by linglung** [comment]
Great! it's worked. You solve my problem and make my day. Thanks so much

**Comment by linglung** [comment]
Great! it's worked. Thanks so much, you explain more good thing than my expected.
it's solve my problem . you make my day.

**Comment by linglung** [comment]
anyway, how do you catch the response log (`Logger.log`) in apps script for telegram bot?

**Comment by albo94** [comment]
Sorry Ocordova! Nine months ago I missed your answer and I discovered it now with these new replies. Last year I solved the problem by myself, but your explanation is great! I thank you so much for your help and the time you spent to solve the problem I asked you! Your initial article and this new explanation are very helpful to implement a telegram bot in Google app script! Thanks!!!

**Comment by ocordova** [comment]
@linglung Been there... I'm sure is not the best solution, but I just send the response values to a spreadsheet :joy:

```javascript

function logUpdate(update){
  var spreadsheet = SpreadsheetApp.openById('{{SPREADSHEET_ID}}');
  var sheet = spreadsheet.getSheetByName('{{TAB_NAME}}')
  sheet.appendRow([update.update_id, update.message.from.username, update.message.chat.id, update.message.text]);
}

```
You can also send an email: 
```javascript
  var update = JSON.parse(e.postData.contents);
  MailApp.sendEmail('zeptok@gmail.com', 'Telegram Bot Request', JSON.stringify(e.postData.contents, null, 2));

```

I think both do the trick  :wink:

**Comment by albo94** [comment]
I always send me a telegram message to debug my functions
as it's not possible to use Logger.log() in doPost(e)
@linglung I solved the problem in the same way of Ocordova

**Comment by linglung** [comment]
@ocordova @albo94  thank to both of you guys. I found many great solution today from this thread.
 it's really useful.  You may close this issue now.  Solved my problem at all. 
have a nice day
